services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: tester
      MYSQL_PASSWORD: tester
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"   # 可选（本地调试用）
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci